### ISSUE TITLE
0/1 indicator variables should be converted to logical (TRUE/FALSE) for use in R

### ISSUE THREAD

**Issue by spkaluzny** [geysertimes/geysertimes-r-package#14]
I think we should convert the 0/1 indicator variables in the eruption data to logical (TRUE, FALSE) in the data set that is created for use in R. R users would naturally expect these types of variables to be represented as logicals. The variables (columns) are:
1. has_seconds
2. exact
3. near_start
4. in_eruption
5. electronic
6. approximate
7. webcam
8. initial
9. major
10. minor
11. questionable

This needs to be decided before I write the details for the help file for the eruptions data `gt_load_eruptions`.

**Comment by taltstidl** [comment]
@spkaluzny Seems reasonable to me, this is probably what users will expect. Go ahead and implement the change :tada:

**Comment by spkaluzny** [comment]
Version 0.0.0.9010 now converts the 0/1 values to FALSE/TRUE in the eruptions dataset.
