### ISSUE TITLE
Open Source License for the Package

### ISSUE THREAD

**Issue by spkaluzny** [geysertimes/geysertimes-r-package#15]
We need to decide on the open source license to release the `geysertimes` package under. Currently, I have used the MIT license in the License field of the DESCRIPTION file. I needed to have a valid value in that field so I can run R CMD check on the package.

A list of open source licenses used by R packages is available here:  https://www.r-project.org/Licenses/

**Comment by taltstidl** [comment]
@spkaluzny I've discussed this internally with the team and we're fine with the MIT license. It's simple and permissive and thus does the job. Any objections on your part?

**Comment by spkaluzny** [comment]
Great, let's go with the MIT license. And the package is already set up for it.

**Comment by spkaluzny** [comment]
Closed with the package under the MIT license.
