### ISSUE TITLE
DESCRIPTION file Author fields

### ISSUE THREAD

**Issue by spkaluzny** [geysertimes/geysertimes-r-package#16]
I want to post the current version of the geysertimes package to CRAN. I will be the Maintainer of the package and listed in the Author field. What other authors should be be listed? The relevant information about the Maintainer and Authors from the Writing R Extensions document (http://cran.fhcrc.org/doc/manuals/r-release/R-exts.html):

> The mandatory ‘Author’ field describes who wrote the package. It is a plain text field intended for human readers, but not for automatic processing (such as extracting the email addresses of all listed contributors: for that use ‘Authors@R’). Note that all significant contributors must be included: if you wrote an R wrapper for the work of others included in the src directory, you are not the sole (and maybe not even the main) author.

> The mandatory ‘Maintainer’ field should give a single name followed by a valid (RFC 2822) email address in angle brackets. It should not end in a period or comma. This field is what is reported by the maintainer function and used by bug.report. For a CRAN package it should be a person, not a mailing list and not a corporate entity: do ensure that it is valid and will remain valid for the lifetime of the package.

> Note that the display name (the part before the address in angle brackets) should be enclosed in double quotes if it contains non-alphanumeric characters such as comma or period. (The current standard, RFC 5322, allows periods but RFC 2822 did not.)

> Both ‘Author’ and ‘Maintainer’ fields can be omitted if a suitable ‘Authors@R’ field is given. This field can be used to provide a refined and machine-readable description of the package “authors” (in particular specifying their precise roles), via suitable R code. It should create an object of class "person", by either a call to person or a series of calls (one per “author”) concatenated by c(): see the example DESCRIPTION file above. The roles can include ‘"aut"’ (author) for full authors, ‘"cre"’ (creator) for the package maintainer, and ‘"ctb"’ (contributor) for other contributors, ‘"cph"’ (copyright holder, which should be the legal name for an institution or corporate body), among others. See ?person for more information. Note that no role is assumed by default. Auto-generated package citation information takes advantage of this specification. The ‘Author’ and ‘Maintainer’ fields are auto-generated from it if needed when building5 or installing. 

Is everything else in the DESCRIPTION file OK?

**Comment by taltstidl** [comment]
@spkaluzny Sorry for not getting back to you earlier. I've been pretty busy working on my master thesis lately and didn't have the time to keep track of many other projects. Since none of us contributed any significant code to this package, I believe it is appropriate to name you as the only author. Thanks for all the work you put into this package :tada: Other fields in the description file also look good to me, we can always refine the title and description as the project grows, I'd assume.

Also, a Merry Christmas to you :santa: :christmas_tree: and a Happy New Year :fireworks: (which in many aspects can only be better than this one)

**Comment by spkaluzny** [comment]
Closing, as the `DESCRIPTION` file is good now.
