### ISSUE TITLE
This repo could use a README

### ISSUE THREAD

**Issue by glennon** [geysertimes/geysertimes-r-package#9]
I get asked a lot about R for doing geyser eruption analysis (especially for Old Faithful data), so it would be useful to have a basic description of this package.

**Comment by taltstidl** [comment]
This is definitely a must - once the package actually makes its way to a stable release. Currently it is very much a work in progress and there's not really much to write about. Work started over a year ago, but has failed to gain significant traction. More contributors would be welcome.

**Comment by hathawayj** [comment]
My student decided to do other work and I haven't had any others that wanted to take up the baton.  The soonest I will be able to find some support is Fall 2020.

**Comment by codemasta14** [comment]
I can pick back work on it in a few weeks.

Cody Jorgensen

On Jun 8, 2020, at 6:04 AM, TR4Android <notifications@github.com> wrote:

﻿

This is definitely a must - once the package actually makes its way to a stable release. Currently it is very much a work in progress and there's not really much to write about. Work started over a year ago, but has failed to gain significant traction. More contributors would be welcome.

**Comment by codemasta14** [comment]
Actually, I’m not going to be able to. I’m terribly sorry.

Cody Jorgensen

On Jun 8, 2020, at 12:12 PM, Jorgensen, Cody <jor15003@byui.edu> wrote:

﻿ I can pick back work on it in a few weeks.

Cody Jorgensen

On Jun 8, 2020, at 6:04 AM, TR4Android <notifications@github.com> wrote:

﻿

This is definitely a must - once the package actually makes its way to a stable release. Currently it is very much a work in progress and there's not really much to write about. Work started over a year ago, but has failed to gain significant traction. More contributors would be welcome.

**Comment by spkaluzny** [comment]
We have a working version of the package. There are several open issues that need to be resolved by someone who knows more about the actual data and the database. I currently have time to devote to the project. Right now I am looking into adding functions to download the geyser locations. I want to be able to add maps to the vignette.

**Comment by taltstidl** [comment]
@spkaluzny Thanks for getting back with us. I'll take care of responding to any remaining issues as swiftly as I can. Mapping capabilities would certainly be appreciated since it eliminates the need to switch tool context, but it should nevertheless be noted that we provide a [web map](https://geysertimes.org/map.php) that people can use.

**Comment by spkaluzny** [comment]
I edited the README.md that @TR4Android created. I pushed it to what I thought was the add-readme branch, not sure. The add-readme branch includes a quickstart.jpeg. I think we should drop, having a jpeg at the top level of a package will not be allowed on CRAN and don't think it will be important once we have a full vignette.

**Comment by taltstidl** [comment]
@spkaluzny Thanks for the finishing touches to my messy R code. The add-readme branch is the correct one :+1:
We can remove the quickstart.jpeg if it's not allowed on CRAN. I had people in mind that browse GitHub, and in my experience the Readmes there are often heavy in images. I'll delete the actual image and then merge the pull request tomorrow.

**Comment by taltstidl** [comment]
@hathawayj I've closed this issue since it's specifically for the Readme, but do ping us if you have someone who's willing to work on this package. We'll gladly add that student to this repo. Thanks.
